=== metadatacenter/cedar-model-validation-library/schema/staticTemplateField.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Meta-schema that describes the schema of a static template field",
    "type": "object",
    "properties": {
        "$schema": {
            "description": "Schema describing the JSON Schema '$schema' field in a template, element, and field",
            "type": "string", "format": "uri",
            "enum": [ "http://json-schema.org/draft-04/schema#" ]
        },
        "type": {
            "description": "Schema describing the JSON Schema 'type' field in a template, element, and field",
            "type": "string", "enum": [ "object" ]
        },
        "schema:name": {
            "description": "Schema describing the template field name",
            "type": "string", "minLength": 1
        },
        "schema:description": {
            "description": "Schema describing the template field description",
            "type": "string"
        },
        "skos:prefLabel": {
            "description": "Schema describing the preferred label, if any",
            "type": "string"
        },
        "title": {
            "description": "Schema describing the JSON Schema 'title' field in a template, element, and field",
            "type": "string", "minLength": 1
        },
        "description": {
            "description": "Schema describing the JSON Schema 'description' field in a template, element, and field",
            "type": "string", "minLength": 1
        },
        "_ui": {
            "$ref": "#/definitions/staticFieldUIContent"
        },
        "@context": {
            "description": "Schema describing the '@context' of a static template field",
            "type": "object",
            "properties": {
                "schema": { "type": "string", "format": "uri", "enum": [ "http://schema.org/" ] },
                "pav": { "type": "string", "format": "uri", "enum": [ "http://purl.org/pav/" ] },
                "oslc": { "type": "string", "format": "uri", "enum": [ "http://open-services.net/ns/core#" ] }
            },
            "required": [ "schema", "pav", "oslc" ]
        },
        "@id": {
            "type": [ "string", "null" ], "format": "uri"
        },
        "@type": {
            "type": "string",
            "format": "uri",
            "enum": [ "https://schema.metadatacenter.org/core/StaticTemplateField" ]
        },
        "properties": {},
        "pav:createdOn": {
            "type": [ "string", "null" ], "format": "date-time"
        },
        "pav:createdBy":  {
            "type": [ "string", "null" ], "format": "uri"
        },
        "pav:lastUpdatedOn":  {
            "type": [ "string", "null" ], "format": "date-time"
        },
        "oslc:modifiedBy": {
            "type": [ "string", "null" ], "format": "uri"
        },
        "schema:schemaVersion": {
            "type": "string", "enum": [ "1.6.0" ]
        },
        "bibo:status": {
            "type": "string", "enum": [ "bibo:published", "bibo:draft" ]
        },
        "additionalProperties": {
            "description": "Schema describing the JSON Schema 'additionalProperties' field in a template, element, and field",
            "type": "boolean", "enum": [ false ]
        }
    },
    "required": [ "$schema", "type", "title", "description", "_ui", "@id", "@type",
        "additionalProperties", "pav:createdOn", "pav:createdBy", "pav:lastUpdatedOn", "oslc:modifiedBy",
        "schema:name", "schema:description", "schema:schemaVersion"  ]
}

=== metadatacenter/cedar-model-validation-library/src/test/resources/fields/section-break.json
{
  "@type": "https://schema.metadatacenter.org/core/StaticTemplateField",
  "@context": {
    "schema": "http://schema.org/",
    "pav": "http://purl.org/pav/",
    "bibo": "http://purl.org/ontology/bibo/",
    "oslc": "http://open-services.net/ns/core#"
  },
  "type": "object",
  "title": "This is a section break field schema",
  "description": "This is a section break field schema generated by the CEDAR Template Editor 2.1.11",
  "_ui": {
    "inputType": "section-break",
    "_content": null
  },
  "pav:createdOn": "2018-11-12T13:31:51-0800",
  "pav:createdBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
  "pav:lastUpdatedOn": "2018-11-12T13:31:51-0800",
  "oslc:modifiedBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
  "schema:schemaVersion": "1.6.0",
  "schema:description": "Help Text",
  "additionalProperties": false,
  "schema:name": "This is a section break",
  "@id": "https://repo.staging.metadatacenter.org/template-fields/bc0f30ee-d08d-4431-b5b1-cbc4e69119c8",
  "$schema": "http://json-schema.org/draft-04/schema#"
}

=== metadatacenter/cedar-model-validation-library/src/test/resources/fields/rich-text-field.json
{
  "@type": "https://schema.metadatacenter.org/core/StaticTemplateField",
  "@context": {
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "pav": "http://purl.org/pav/",
    "bibo": "http://purl.org/ontology/bibo/",
    "oslc": "http://open-services.net/ns/core#",
    "schema": "http://schema.org/",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "schema:name": {
      "@type": "xsd:string"
    },
    "schema:description": {
      "@type": "xsd:string"
    },
    "skos:prefLabel": {
      "@type": "xsd:string"
    },
    "skos:altLabel": {
      "@type": "xsd:string"
    },
    "pav:createdOn": {
      "@type": "xsd:dateTime"
    },
    "pav:createdBy": {
      "@type": "@id"
    },
    "pav:lastUpdatedOn": {
      "@type": "xsd:dateTime"
    },
    "oslc:modifiedBy": {
      "@type": "@id"
    }
  },
  "type": "object",
  "title": "What is a template? field schema",
  "description": "What is a template? field schema generated by the CEDAR Template Editor 2.1.11",
  "_ui": {
    "inputType": "richtext",
    "_content": "<p>Lorem ipsum</p>\n"
  },
  "pav:createdOn": "2018-11-12T13:31:51-0800",
  "pav:createdBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
  "pav:lastUpdatedOn": "2018-11-12T13:31:51-0800",
  "oslc:modifiedBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
  "schema:schemaVersion": "1.6.0",
  "schema:description": "Help Text",
  "additionalProperties": false,
  "schema:name": "What is a template?",
  "@id": "https://repo.staging.metadatacenter.org/template-fields/8be2ca75-f253-4e1c-9d46-e9126c7c694e",
  "$schema": "http://json-schema.org/draft-04/schema#"
}

=== metadatacenter/cedar-model-validation-library/src/test/resources/fields/video-field.json
{
  "@type": "https://schema.metadatacenter.org/core/StaticTemplateField",
  "@context": {
    "schema": "http://schema.org/",
    "pav": "http://purl.org/pav/",
    "bibo": "http://purl.org/ontology/bibo/",
    "oslc": "http://open-services.net/ns/core#"
  },
  "type": "object",
  "title": "Untitled field schema",
  "description": "Untitled field schema generated by the CEDAR Template Editor 2.1.11",
  "_ui": {
    "inputType": "youtube",
    "_content": "12345678"
  },
  "pav:createdOn": "2018-11-12T13:31:51-0800",
  "pav:createdBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
  "pav:lastUpdatedOn": "2018-11-12T13:31:51-0800",
  "oslc:modifiedBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
  "schema:schemaVersion": "1.6.0",
  "schema:description": "Help Text",
  "additionalProperties": false,
  "schema:name": "Untitled",
  "@id": "https://repo.staging.metadatacenter.org/template-fields/d82687b5-5cf2-4373-a128-93e22df56a17",
  "$schema": "http://json-schema.org/draft-04/schema#"
}

=== metadatacenter/cedar-model-validation-library/src/test/resources/fields/image-field.json
{
  "@type": "https://schema.metadatacenter.org/core/StaticTemplateField",
  "@context": {
    "schema": "http://schema.org/",
    "pav": "http://purl.org/pav/",
    "bibo": "http://purl.org/ontology/bibo/",
    "oslc": "http://open-services.net/ns/core#"
  },
  "type": "object",
  "title": "Cell image field schema",
  "description": "Cell image field schema generated by the CEDAR Template Editor 2.1.11",
  "_ui": {
    "inputType": "image",
    "_content": "https://example.org/cell-image.jpg"
  },
  "pav:createdOn": "2018-11-12T13:31:51-0800",
  "pav:createdBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
  "pav:lastUpdatedOn": "2018-11-12T13:31:51-0800",
  "oslc:modifiedBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
  "schema:schemaVersion": "1.6.0",
  "schema:description": "Help Text",
  "additionalProperties": false,
  "schema:name": "Cell image",
  "@id": "https://repo.staging.metadatacenter.org/template-fields/5b2d1d05-ff24-4a8e-9c8f-f7f976775cdb",
  "$schema": "http://json-schema.org/draft-04/schema#"
}

=== metadatacenter/cedar-model-validation-library/src/test/resources/fields/page-break.json
{
  "@type": "https://schema.metadatacenter.org/core/StaticTemplateField",
  "@context": {
    "schema": "http://schema.org/",
    "pav": "http://purl.org/pav/",
    "bibo": "http://purl.org/ontology/bibo/",
    "oslc": "http://open-services.net/ns/core#"
  },
  "type": "object",
  "title": "This is a page break field schema",
  "description": "This is a page break field schema generated by the CEDAR Template Editor 2.1.11",
  "_ui": {
    "inputType": "page-break",
    "_content": null
  },
  "pav:createdOn": "2018-11-12T13:31:51-0800",
  "pav:createdBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
  "pav:lastUpdatedOn": "2018-11-12T13:31:51-0800",
  "oslc:modifiedBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
  "schema:schemaVersion": "1.6.0",
  "schema:description": "Help Text",
  "additionalProperties": false,
  "schema:name": "This is a page break",
  "@id": "https://repo.staging.metadatacenter.org/template-fields/ae0fb67e-2f3a-437c-a3b6-b7a61d8ce8a6",
  "$schema": "http://json-schema.org/draft-04/schema#"
}
