=== metadatacenter/cedar-model-validation-library/schema/templateElement.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Meta-schema that describes the schema of a template element",
    "type": "object",
    "properties": {
        "$schema": {
            "description": "Schema describing the JSON Schema '$schema' field in a template, element, and field",
            "type": "string", "format": "uri",
            "enum": [ "http://json-schema.org/draft-04/schema#" ]
        },
        "type": {
            "description": "Schema describing the JSON Schema 'type' field in a template, element, and field",
            "type": "string", "enum": [ "object", "array" ]
        },
        "schema:identifier": {
          "description": "Schema describing the template element's user-defined identifier",
          "type": "string", "minLength": 1
        },
        "schema:name": {
            "description": "Schema describing the template element name",
            "type": "string", "minLength": 1
        },
        "schema:description": {
            "description": "Schema describing the template element description",
            "type": "string"
        },
        "skos:prefLabel": {
            "description": "Schema describing the preferred label, if any",
            "type": "string"
        },
        "skos:altLabel": {
            "description": "Schema describing the alternative labels, if any",
            "type": "array", "uniqueItems": true
        },
        "title": {
            "description": "Schema describing the JSON Schema 'title' field in a template, element, and field",
            "type": "string", "minLength": 1
        },
        "description": {
            "description": "Schema describing the JSON Schema 'description' field in a template, element, and field",
            "type": "string", "minLength": 1
        },
        "_ui": {
            "$ref": "#/definitions/templateElementUIFieldContent"
        },
        "@context": {
            "$ref": "#/definitions/templateElementJSONLDContextFieldContent"
        },
        "@id": {
            "type": [ "string", "null" ], "format": "uri"
        },
        "@type": {
            "type": "string", "format": "uri", "enum": [ "https://schema.metadatacenter.org/core/TemplateElement" ]
        },
        "properties": {
            "$ref": "#/definitions/templateElementPropertiesFieldContent"
        },
        "required": {
            "$ref": "#/definitions/templateElementRequiredContent"
        },
        "pav:createdOn": {
            "type": [ "string", "null" ], "format": "date-time"
        },
        "pav:createdBy":  {
            "type": [ "string", "null" ], "format": "uri"
        },
        "pav:lastUpdatedOn":  {
            "type": [ "string", "null" ], "format": "date-time"
        },
        "oslc:modifiedBy": {
            "type": [ "string", "null" ], "format": "uri"
        },
        "additionalProperties": {
          "oneOf": [
            { "$ref": "file:falseOnlyAdditionalProperties.json" },
            { "$ref": "file:defaultObjectSchemaAdditionalProperties.json" }
          ]
        },
        "schema:schemaVersion": {
            "type": "string", "enum": [ "1.6.0" ]
        },
        "bibo:status": {
            "type": "string", "enum": [ "bibo:published", "bibo:draft" ]
        },
        "pav:version": {
            "type": "string", "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$"
        },
        "pav:previousVersion": {
            "type": "string", "minLength": 1
        },
        "pav:derivedFrom": {
            "type": "string", "format": "uri"
        },
        "@nest": {
          "$ref": "#/definitions/nestFieldContent.json"
        }
    },
    "required": [ "$schema", "type", "title", "description", "_ui", "@context", "@id", "@type", "properties", "required",
        "pav:createdOn", "pav:createdBy", "pav:lastUpdatedOn", "oslc:modifiedBy", "schema:schemaVersion", "schema:name",
        "schema:description" ]
}

=== metadatacenter/cedar-model-validation-library/src/test/resources/elements/attribute-value-element.json
{
  "@id": "https://repo.staging.metadatacenter.org/template-elements/b8088312-91a8-4e66-aa74-98d2c5e10adc",
  "@type": "https://schema.metadatacenter.org/core/TemplateElement",
  "@context": {
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "pav": "http://purl.org/pav/",
    "bibo": "http://purl.org/ontology/bibo/",
    "oslc": "http://open-services.net/ns/core#",
    "schema": "http://schema.org/",
    "schema:name": {
      "@type": "xsd:string"
    },
    "schema:description": {
      "@type": "xsd:string"
    },
    "pav:createdOn": {
      "@type": "xsd:dateTime"
    },
    "pav:createdBy": {
      "@type": "@id"
    },
    "pav:lastUpdatedOn": {
      "@type": "xsd:dateTime"
    },
    "oslc:modifiedBy": {
      "@type": "@id"
    }
  },
  "type": "object",
  "title": "Attribute value example element schema",
  "description": "Attribute value example element schema generated by the CEDAR Template Editor 2.1.11",
  "_ui": {
    "order": [
      "Name",
      "Additional Information"
    ],
    "propertyLabels": {
      "Name": "Name",
      "Additional Information": "Additional Information"
    },
    "propertyDescriptions": {
      "Name": "Help Text",
      "Additional Information": "Help Text"
    }
  },
  "properties": {
    "@context": {
      "type": "object",
      "properties": {
        "Name": {
          "enum": [
            "https://schema.staging.metadatacenter.org/properties/c50938ee-b4ab-42be-8023-b3386c6e7db7"
          ]
        }
      },
      "additionalProperties": {
        "type": "string",
        "format": "uri"
      },
      "required": [
        "Name"
      ]
    },
    "@id": {
      "type": "string",
      "format": "uri"
    },
    "@type": {
      "oneOf": [
        {
          "type": "string",
          "format": "uri"
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "format": "uri"
          },
          "uniqueItems": true
        }
      ]
    },
    "Name": {
      "@type": "https://schema.metadatacenter.org/core/TemplateField",
      "@context": {
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "pav": "http://purl.org/pav/",
        "bibo": "http://purl.org/ontology/bibo/",
        "oslc": "http://open-services.net/ns/core#",
        "schema": "http://schema.org/",
        "skos": "http://www.w3.org/2004/02/skos/core#",
        "schema:name": {
          "@type": "xsd:string"
        },
        "schema:description": {
          "@type": "xsd:string"
        },
        "skos:prefLabel": {
          "@type": "xsd:string"
        },
        "skos:altLabel": {
          "@type": "xsd:string"
        },
        "pav:createdOn": {
          "@type": "xsd:dateTime"
        },
        "pav:createdBy": {
          "@type": "@id"
        },
        "pav:lastUpdatedOn": {
          "@type": "xsd:dateTime"
        },
        "oslc:modifiedBy": {
          "@type": "@id"
        }
      },
      "type": "object",
      "title": "Name field schema",
      "description": "Name field schema generated by the CEDAR Template Editor 2.1.11",
      "_ui": {
        "inputType": "textfield"
      },
      "_valueConstraints": {
        "requiredValue": false
      },
      "properties": {
        "@type": {
          "oneOf": [
            {
              "type": "string",
              "format": "uri"
            },
            {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string",
                "format": "uri"
              },
              "uniqueItems": true
            }
          ]
        },
        "@value": {
          "type": [
            "string",
            "null"
          ]
        },
        "rdfs:label": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "@value"
      ],
      "schema:name": "Name",
      "schema:description": "Help Text",
      "pav:createdOn": "2018-11-12T10:20:23-0800",
      "pav:createdBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
      "pav:lastUpdatedOn": "2018-11-12T10:20:23-0800",
      "oslc:modifiedBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
      "schema:schemaVersion": "1.6.0",
      "additionalProperties": false,
      "@id": "https://repo.staging.metadatacenter.org/template-fields/f995aa8a-5263-45d8-a82f-9f855885e8e4",
      "$schema": "http://json-schema.org/draft-04/schema#"
    },
    "Additional Information": {
      "type": "array",
      "minItems": 0,
      "items": {
        "@context": {
          "xsd": "http://www.w3.org/2001/XMLSchema#",
          "pav": "http://purl.org/pav/",
          "bibo": "http://purl.org/ontology/bibo/",
          "oslc": "http://open-services.net/ns/core#",
          "schema": "http://schema.org/",
          "skos": "http://www.w3.org/2004/02/skos/core#",
          "schema:name": {
            "@type": "xsd:string"
          },
          "schema:description": {
            "@type": "xsd:string"
          },
          "skos:prefLabel": {
            "@type": "xsd:string"
          },
          "skos:altLabel": {
            "@type": "xsd:string"
          },
          "pav:createdOn": {
            "@type": "xsd:dateTime"
          },
          "pav:createdBy": {
            "@type": "@id"
          },
          "pav:lastUpdatedOn": {
            "@type": "xsd:dateTime"
          },
          "oslc:modifiedBy": {
            "@type": "@id"
          }
        },
        "@type": "https://schema.metadatacenter.org/core/TemplateField",
        "type": "string",
        "title": "Additional Information field schema",
        "description": "Additional Information field schema generated by the CEDAR Template Editor 2.1.11",
        "_ui": {
          "inputType": "attribute-value"
        },
        "schema:name": "Additional Information",
        "schema:description": "Help Text",
        "pav:createdOn": "2018-11-12T10:20:23-0800",
        "pav:createdBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
        "pav:lastUpdatedOn": "2018-11-12T10:20:23-0800",
        "oslc:modifiedBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
        "schema:schemaVersion": "1.6.0",
        "additionalProperties": false,
        "@id": "https://repo.staging.metadatacenter.org/template-fields/9800e64b-32a5-441c-b09b-1f9dbe357090",
        "$schema": "http://json-schema.org/draft-04/schema#"
      }
    }
  },
  "schema:name": "Attribute Value Example",
  "schema:description": "",
  "required": [
    "@context",
    "@id",
    "Name"
  ],
  "pav:createdOn": "2018-11-12T10:20:23-0800",
  "pav:createdBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
  "pav:lastUpdatedOn": "2018-11-12T10:20:23-0800",
  "oslc:modifiedBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
  "schema:schemaVersion": "1.6.0",
  "additionalProperties": {
    "type": "object",
    "properties": {
      "@value": {
        "type": [
          "string",
          "null"
        ]
      },
      "@type": {
        "type": "string",
        "format": "uri"
      }
    },
    "required": [
      "@value"
    ],
    "additionalProperties": false
  },
  "pav:version": "0.0.1",
  "bibo:status": "bibo:draft",
  "$schema": "http://json-schema.org/draft-04/schema#"
}
