=== metadatacenter/cedar-model-validation-library/schema/template.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Meta-schema that describes the schema of a template",
    "type": "object",
    "properties": {
        "$schema": {
            "description": "Schema describing the JSON Schema '$schema' field in a template, element, and field",
            "type": "string", "format": "uri",
            "enum": [ "http://json-schema.org/draft-04/schema#" ]
        },
        "type": {
            "description": "Schema describing the JSON Schema 'type' field in a template, element, and field",
            "type": "string", "enum": [ "object", "array" ]
        },
        "schema:identifier": {
          "description": "Schema describing the template's user-defined identifier",
          "type": "string", "minLength": 1
        },
        "schema:name": {
            "description": "Schema describing the template name",
            "type": "string", "minLength": 1
        },
        "schema:description": {
            "description": "Schema describing the template description",
            "type": "string"
        },
        "title": {
            "description": "Schema describing the JSON Schema 'title' field in a template, element, and field",
            "type": "string", "minLength": 1
        },
        "description": {
            "description": "Schema describing the JSON Schema 'description' field in a template, element, and field",
            "type": "string", "minLength": 1
        },
        "_ui": {
            "$ref": "#/definitions/templateUIFieldContent"
        },
        "@context": {
            "$ref": "#/definitions/templateJSONLDContextFieldContent"
        },
        "@id": {
            "type": [ "string", "null" ], "format": "uri"
        },
        "@type": {
            "type": "string", "format": "uri",
            "enum": [ "https://schema.metadatacenter.org/core/Template" ]
        },
        "properties": {
            "$ref": "#/definitions/templatePropertiesFieldContent"
        },
        "required": {
            "$ref": "#/definitions/templateRequiredFieldContent"
        },
        "pav:createdOn": {
            "type": [ "string", "null" ], "format": "date-time"
        },
        "pav:createdBy":  {
            "type": [ "string", "null" ], "format": "uri"
        },
        "pav:lastUpdatedOn":  {
            "type": [ "string", "null" ], "format": "date-time"
        },
        "oslc:modifiedBy": {
            "type": [ "string", "null" ], "format": "uri"
        },
        "schema:schemaVersion": {
            "type": "string", "enum": [ "1.6.0" ]
        },
        "bibo:status": {
            "type": "string", "enum": [ "bibo:published", "bibo:draft" ]
        },
        "pav:version": {
            "type": "string", "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$"
        },
        "pav:previousVersion": {
            "type": "string", "minLength": 1
        },
        "pav:derivedFrom": {
            "type": "string", "format": "uri"
        },
        "_annotations": {
            "$ref": "#/definitions/annotationsContent.json"
        },
        "additionalProperties": {
          "oneOf": [
            { "$ref": "#/definitions/falseOnlyAdditionalProperties.json" },
            { "$ref": "#/definitions/defaultObjectSchemaAdditionalProperties.json" }
          ]
        },
        "@nest": {
          "$ref": "#/definitions/nestFieldContent.json"
        }
    },
    "required": [ "$schema", "type", "title", "description", "_ui", "@context", "@id", "@type", "properties", "required",
        "pav:createdOn", "pav:createdBy", "pav:lastUpdatedOn", "oslc:modifiedBy", "schema:schemaVersion", "schema:name",
        "schema:description" ]
}

=== metadatacenter/cedar-model-validation-library/src/test/resources/templates/single-field-template.json
{
  "@id": "https://repo.staging.metadatacenter.org/templates/dc898011-2742-41e9-9dae-9b57dbf2600f",
  "@type": "https://schema.metadatacenter.org/core/Template",
  "@context": {
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "pav": "http://purl.org/pav/",
    "bibo": "http://purl.org/ontology/bibo/",
    "oslc": "http://open-services.net/ns/core#",
    "schema": "http://schema.org/",
    "schema:name": {
      "@type": "xsd:string"
    },
    "schema:description": {
      "@type": "xsd:string"
    },
    "pav:createdOn": {
      "@type": "xsd:dateTime"
    },
    "pav:createdBy": {
      "@type": "@id"
    },
    "pav:lastUpdatedOn": {
      "@type": "xsd:dateTime"
    },
    "oslc:modifiedBy": {
      "@type": "@id"
    }
  },
  "type": "object",
  "title": "Single field template template schema",
  "description": "Single field template template schema generated by the CEDAR Template Editor 2.1.11",
  "_ui": {
    "order": [
      "Study Name"
    ],
    "propertyLabels": {
      "f364c4d0-e9af-483b-8b56-85686f2f94bd": "Study Name",
      "Study Name": "Study Name"
    },
    "propertyDescriptions": {
      "Study Name": "Help Text"
    }
  },
  "properties": {
    "@context": {
      "type": "object",
      "properties": {
        "rdfs": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://www.w3.org/2000/01/rdf-schema#"
          ]
        },
        "xsd": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://www.w3.org/2001/XMLSchema#"
          ]
        },
        "pav": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://purl.org/pav/"
          ]
        },
        "schema": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://schema.org/"
          ]
        },
        "oslc": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://open-services.net/ns/core#"
          ]
        },
        "skos": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://www.w3.org/2004/02/skos/core#"
          ]
        },
        "rdfs:label": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:string"
              ]
            }
          }
        },
        "schema:isBasedOn": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "@id"
              ]
            }
          }
        },
        "schema:name": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:string"
              ]
            }
          }
        },
        "schema:description": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:string"
              ]
            }
          }
        },
        "pav:createdOn": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:dateTime"
              ]
            }
          }
        },
        "pav:createdBy": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "@id"
              ]
            }
          }
        },
        "pav:lastUpdatedOn": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:dateTime"
              ]
            }
          }
        },
        "oslc:modifiedBy": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "@id"
              ]
            }
          }
        },
        "skos:notation": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:string"
              ]
            }
          }
        },
        "pav:derivedFrom": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "@id"
              ]
            }
          }
        },
        "@language": {
          "type": [ "string", "null"],
          "minLength": 1
         },
        "Study Name": {
          "enum": [
            "https://schema.staging.metadatacenter.org/properties/de3eece8-0bab-4eb7-b382-4b26a6a770d8"
          ]
        }
      },
      "required": [
        "xsd",
        "pav",
        "schema",
        "oslc",
        "schema:isBasedOn",
        "schema:name",
        "schema:description",
        "pav:createdOn",
        "pav:createdBy",
        "pav:lastUpdatedOn",
        "oslc:modifiedBy"
      ],
      "additionalProperties": false
    },
    "@id": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "@type": {
      "oneOf": [
        {
          "type": "string",
          "format": "uri"
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "format": "uri"
          },
          "uniqueItems": true
        }
      ]
    },
    "schema:isBasedOn": {
      "type": "string",
      "format": "uri"
    },
    "schema:name": {
      "type": "string",
      "minLength": 1
    },
    "schema:description": {
      "type": "string"
    },
    "pav:createdOn": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "pav:createdBy": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "pav:lastUpdatedOn": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "oslc:modifiedBy": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "pav:derivedFrom": {
      "type": "string",
      "format": "uri"
    },
    "Study Name": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "@id": "tmp-1542047882174-1714355",
      "@type": "https://schema.metadatacenter.org/core/TemplateField",
      "@context": {
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "pav": "http://purl.org/pav/",
        "bibo": "http://purl.org/ontology/bibo/",
        "oslc": "http://open-services.net/ns/core#",
        "schema": "http://schema.org/",
        "skos": "http://www.w3.org/2004/02/skos/core#",
        "schema:name": {
          "@type": "xsd:string"
        },
        "schema:description": {
          "@type": "xsd:string"
        },
        "skos:prefLabel": {
          "@type": "xsd:string"
        },
        "skos:altLabel": {
          "@type": "xsd:string"
        },
        "pav:createdOn": {
          "@type": "xsd:dateTime"
        },
        "pav:createdBy": {
          "@type": "@id"
        },
        "pav:lastUpdatedOn": {
          "@type": "xsd:dateTime"
        },
        "oslc:modifiedBy": {
          "@type": "@id"
        }
      },
      "type": "object",
      "title": "Study Name field schema",
      "description": "Study Name field schema generated by the CEDAR Template Editor 2.1.11",
      "_ui": {
        "inputType": "textfield"
      },
      "_valueConstraints": {
        "requiredValue": false
      },
      "properties": {
        "@type": {
          "oneOf": [
            {
              "type": "string",
              "format": "uri"
            },
            {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string",
                "format": "uri"
              },
              "uniqueItems": true
            }
          ]
        },
        "@value": {
          "type": [
            "string",
            "null"
          ]
        },
         "@language": {
          "type": [
            "string",
            "null"
          ],
          "minLength": 1
        },
        "rdfs:label": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "@value"
      ],
      "schema:name": "Study Name",
      "schema:description": "Help Text",
      "pav:createdOn": null,
      "pav:createdBy": null,
      "pav:lastUpdatedOn": null,
      "oslc:modifiedBy": null,
      "schema:schemaVersion": "1.6.0",
      "additionalProperties": false
    }
  },
  "required": [
    "@context",
    "@id",
    "schema:isBasedOn",
    "schema:name",
    "schema:description",
    "pav:createdOn",
    "pav:createdBy",
    "pav:lastUpdatedOn",
    "oslc:modifiedBy",
    "Study Name"
  ],
  "schema:name": "Single Field Template",
  "schema:description": "",
  "pav:createdOn": "2018-11-12T10:37:58-0800",
  "pav:createdBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
  "pav:lastUpdatedOn": "2018-11-12T10:37:58-0800",
  "oslc:modifiedBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
  "schema:schemaVersion": "1.6.0",
  "additionalProperties": false,
  "pav:version": "0.0.1",
  "bibo:status": "bibo:draft",
  "$schema": "http://json-schema.org/draft-04/schema#"
}
